import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client.js";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL || "file:./dev.db",
});
const prisma = new PrismaClient({ adapter });

const cards = [
  {
    id: "card_hdfc_regalia_gold",
    name: "HDFC Regalia Gold",
    bank: "HDFC Bank",
    network: "Visa",
    cardType: "credit",
    color: "#004B87",
    annualFee: 2500,
    joiningFee: 2500,
    rewardStructure: "4 Reward Points per ₹150 spent (excluding fuel, wallet loads, EMI). 1 RP = ₹0.50. Effective earn rate: 1.33% on regular spend. 10x points on SmartBuy (flights, hotels, Amazon) = 13.3% return.",
    cashbackStructure: "No direct cashback. Points redeemable for statement credit, vouchers, or air miles. Best value via SmartBuy portal redemptions.",
    loungeAccess: "12 complimentary domestic lounge visits per year (via Visa/DreamFolks). 6 international lounge visits via Priority Pass. Guest access at ₹1,500 per visit.",
    travelBenefits: "Travel insurance cover up to ₹50 lakhs for air accidents. Lost baggage insurance ₹2 lakhs. Trip delay insurance (12+ hours) ₹10,000. SmartBuy 10x on flights and hotels.",
    insuranceBenefits: "Air accident cover ₹1 crore. Lost card liability zero. Purchase protection 90 days. Emergency medical assistance abroad.",
    fuelBenefits: "1% fuel surcharge waiver at all fuel stations. Maximum waiver ₹250 per month. Applicable for transactions ₹400-₹5,000.",
    diningBenefits: "Good Food Trail: 15% off at 1,500+ partner restaurants. Zomato/Swiggy offers periodically. No special reward multiplier for dining.",
    movieBenefits: "Buy 1 Get 1 on BookMyShow (2 free tickets per month, max ₹250 per ticket). Valid for movies, plays, and events.",
    golfBenefits: "Complimentary golf lessons at select courses. 2 rounds per quarter at partner courses.",
    forexMarkup: "3.5% markup on foreign currency transactions (2% markup + 18% GST). Not the best for international travel.",
    milestoneRewards: "Spend ₹5 lakhs in a year: 5,000 bonus reward points. Spend ₹8 lakhs: additional 5,000 bonus points. Annual fee waiver on ₹5L+ spend in some campaigns.",
    welcomeBenefits: "2,500 reward points on card activation (worth ₹1,250). First year fee often waived on relationship value.",
    currentOffers: "SmartBuy 10x on Amazon, Flipkart (up to 5,000 points/month). Milestone bonus: 10,000 points on ₹8L annual spend. EMI conversion at 0% for 3 months on ₹10K+ purchases.",
    bestFor: "Frequent online shoppers (SmartBuy 10x), domestic travelers needing lounge access, BookMyShow regulars. Excellent all-rounder for ₹5-10L annual spend.",
    worstFor: "International travelers (3.5% forex markup is high), fuel-heavy spenders (low fuel benefit cap), high spenders who'd benefit more from premium cards.",
    estimatedAnnualValue: 15000,
    bins: ["524130", "524131", "436583"],
  },
  {
    id: "card_hdfc_millennia",
    name: "HDFC Millennia",
    bank: "HDFC Bank",
    network: "Mastercard",
    cardType: "credit",
    color: "#1A1A2E",
    annualFee: 1000,
    joiningFee: 1000,
    rewardStructure: "5% CashBack on Amazon, Flipkart, Myntra, Swiggy, Zomato, BookMyShow, Uber (capped at ₹750/month). 1% cashback on all other online spends. 2.5% on offline spends via tap-and-pay.",
    cashbackStructure: "CashPoints credited monthly. Max ₹750/month on preferred merchants. 1% on other online. 2.5% on contactless. Statement credit redemption.",
    loungeAccess: "8 complimentary domestic lounge visits per year via DreamFolks. No international lounge access included.",
    travelBenefits: "No dedicated travel insurance. Basic air accident cover ₹50 lakhs. MakeMyTrip offers available periodically.",
    insuranceBenefits: "Air accident cover ₹50 lakhs. Zero lost card liability. Basic purchase protection.",
    fuelBenefits: "1% fuel surcharge waiver (max ₹250/month). Applicable ₹400-₹5,000 per transaction.",
    diningBenefits: "5% CashBack on Swiggy and Zomato (within the ₹750/month cap). Occasional EazyDiner and Dineout partnerships.",
    movieBenefits: "5% CashBack on BookMyShow (within cap). No Buy 1 Get 1 offer.",
    golfBenefits: "None.",
    forexMarkup: "3.5% on international transactions. Not recommended for forex use.",
    milestoneRewards: "Spend ₹1 lakh in 90 days of card issuance: 1,000 bonus CashPoints. Annual spend ₹2 lakhs: fee reversal.",
    welcomeBenefits: "1,000 CashPoints on first spend within 30 days. Essentially ₹1,000 back = free first year.",
    currentOffers: "5% on Amazon Great Indian Festival. Extra 500 CashPoints on 3 tap-and-pay transactions in a month. Swiggy: flat ₹100 off on ₹300+ orders (twice/month).",
    bestFor: "Young professionals spending on food delivery, online shopping, and entertainment. Best entry-level card for digital-first lifestyles under ₹3L annual spend.",
    worstFor: "Heavy offline spenders, international travelers, users wanting lounge access abroad, premium travel benefits.",
    estimatedAnnualValue: 8000,
    bins: ["524028", "524029"],
  },
  {
    id: "card_axis_magnus",
    name: "Axis Bank Magnus",
    bank: "Axis Bank",
    network: "Visa",
    cardType: "credit",
    color: "#97144D",
    annualFee: 12500,
    joiningFee: 12500,
    rewardStructure: "35 EDGE points per ₹200 on travel (MakeMyTrip, Yatra, EaseMyTrip via EDGE portal). 12 EDGE points per ₹200 on all other spends. 1 EDGE point ≈ ₹0.50. Effective rate: 3% on regular spend.",
    cashbackStructure: "No direct cashback. EDGE Points redeemable for air miles (1:1 InterMiles), hotel stays, statement credit. Best value transferring to airline partners.",
    loungeAccess: "Unlimited domestic and international lounge access via Priority Pass for cardholder + guest. No cap on visits. One of the best lounge propositions in India.",
    travelBenefits: "Accor Plus Explorer membership (free night at 1,100+ Accor hotels). Complimentary meet & greet at airports. Travel insurance ₹3 crores. Lost baggage ₹5 lakhs. Trip delay ₹25,000.",
    insuranceBenefits: "Air accident cover ₹3 crores. Emergency overseas medical ₹25 lakhs. Lost card zero liability. Purchase protection 120 days.",
    fuelBenefits: "1% fuel surcharge waiver up to ₹500/month. Applicable ₹400-₹5,000 per transaction.",
    diningBenefits: "Dining Delights: 20% off at 4,000+ partner restaurants. Zomato Pro Plus equivalent benefits occasionally.",
    movieBenefits: "Buy 1 Get 1 on BookMyShow (up to ₹500 per ticket, 3 times/month). PVR/INOX privileges.",
    golfBenefits: "Complimentary golf rounds at 20+ courses across India. 4 green fees per quarter. Club hire included.",
    forexMarkup: "2% on foreign currency transactions (among the lowest in India). Excellent for international travel.",
    milestoneRewards: "Spend ₹15 lakhs/year: annual fee reversal as EDGE Points. Spend ₹25 lakhs: additional 25,000 bonus EDGE Points. Transfer bonus to InterMiles periodic.",
    welcomeBenefits: "25,000 EDGE Points on first spend (worth ₹12,500). Accor Plus Explorer membership (worth ₹18,000).",
    currentOffers: "5x EDGE on Flipkart/Amazon (limited period). Transfer 1:1 to InterMiles with 30% bonus (periodic). Duty-free 15% off at Delhi/Mumbai airports.",
    bestFor: "Ultra-premium travelers spending ₹15L+/year. Best lounge card in India. Accor Plus alone can save ₹18K+. Ideal for frequent international flyers.",
    worstFor: "Low spenders (₹12,500 fee needs ₹15L spend to justify). Purely domestic users who don't travel. Those wanting simple cashback.",
    estimatedAnnualValue: 50000,
    bins: ["414720", "414721", "414722"],
  },
  {
    id: "card_axis_atlas",
    name: "Axis Bank Atlas",
    bank: "Axis Bank",
    network: "Visa",
    cardType: "credit",
    color: "#2D3748",
    annualFee: 5000,
    joiningFee: 5000,
    rewardStructure: "5 EDGE Miles per ₹100 on travel spends. 2 EDGE Miles per ₹100 on all other spends. 1 EDGE Mile = ₹0.50-₹1.00 depending on redemption.",
    cashbackStructure: "No cashback. Miles-focused card. Best value when transferred to airline/hotel partners at sweet-spot ratios.",
    loungeAccess: "8 complimentary domestic + 8 international lounge visits per year via Priority Pass. Additional visits at $32 each.",
    travelBenefits: "Travel insurance ₹1 crore. Lost baggage cover ₹1 lakh. Flight delay insurance. Preferential forex rate on select currencies.",
    insuranceBenefits: "Air accident cover ₹1 crore. Zero liability on fraud. Purchase protection 90 days. Emergency medical ₹15 lakhs abroad.",
    fuelBenefits: "1% fuel surcharge waiver up to ₹400/month. Standard ₹400-₹5,000 range.",
    diningBenefits: "Dining Delights: 15% off at partner restaurants. Swiggy/Zomato periodic offers.",
    movieBenefits: "Buy 1 Get 1 on BookMyShow (2 times/month, max ₹300 per ticket).",
    golfBenefits: "2 complimentary rounds per quarter at select courses.",
    forexMarkup: "2.5% on international transactions. Better than average but not best-in-class.",
    milestoneRewards: "Spend ₹7.5 lakhs/year: 10,000 bonus EDGE Miles. Spend ₹15 lakhs: additional 15,000 bonus miles + fee waiver.",
    welcomeBenefits: "5,000 EDGE Miles on first spend within 45 days (worth ₹2,500-₹5,000). 500 miles on first EMI conversion.",
    currentOffers: "Double miles on international spends this quarter. Transfer 2:1 to Vistara ClubVistara with 20% bonus. Amazon 5x miles (limited period).",
    bestFor: "Mid-range travelers (₹7-15L spend). Great miles-earning card for those who transfer to airline partners. Good lounge access for the fee.",
    worstFor: "Non-travelers, cashback seekers, those spending under ₹5L/year (hard to recoup the ₹5,000 fee).",
    estimatedAnnualValue: 25000,
    bins: ["414730", "414731"],
  },
  {
    id: "card_sbi_cashback",
    name: "SBI Cashback",
    bank: "SBI Card",
    network: "Visa",
    cardType: "credit",
    color: "#22409A",
    annualFee: 999,
    joiningFee: 999,
    rewardStructure: "5% cashback on all online spends (Amazon, Flipkart, Swiggy, BigBasket, etc.). 1% cashback on offline spends. Maximum cashback ₹5,000 per statement cycle.",
    cashbackStructure: "Flat 5% online / 1% offline. Cashback credited as statement credit. No categories to track. Simple and transparent. Monthly cap ₹5,000.",
    loungeAccess: "4 domestic lounge visits per year via RuPay/Visa network. No international lounge access.",
    travelBenefits: "No dedicated travel benefits. Basic air accident cover only.",
    insuranceBenefits: "Air accident cover ₹25 lakhs. Zero lost card liability. No medical or travel insurance.",
    fuelBenefits: "1% fuel surcharge waiver (max ₹100/month). Applicable ₹500-₹3,000 transactions.",
    diningBenefits: "1% cashback on restaurant dining (offline rate). No special dining partnerships.",
    movieBenefits: "No movie-specific benefits.",
    golfBenefits: "None.",
    forexMarkup: "3.5% on international transactions. Not recommended for forex.",
    milestoneRewards: "Spend ₹2 lakhs/year: annual fee waiver for next year. No other milestone rewards.",
    welcomeBenefits: "₹500 Amazon voucher on first spend within 60 days.",
    currentOffers: "Extra 1% cashback on BigBasket orders (total 6%). SBI exclusive: 10% instant discount on Tata CLiQ (max ₹1,500). Zero-cost EMI on ₹5K+ at electronics stores.",
    bestFor: "Online shopping enthusiasts who want simple, no-nonsense 5% cashback. Best cashback card under ₹1,000 annual fee in India.",
    worstFor: "Offline spenders (only 1%), travelers needing lounges/insurance, anyone wanting premium experiences or miles accumulation.",
    estimatedAnnualValue: 6000,
    bins: ["436590", "436591"],
  },
  {
    id: "card_icici_amazon",
    name: "ICICI Amazon Pay",
    bank: "ICICI Bank",
    network: "Visa",
    cardType: "credit",
    color: "#FF9900",
    annualFee: 500,
    joiningFee: 0,
    rewardStructure: "5% back on Amazon.in for Prime members (2% for non-Prime). 2% back on paying bills, recharges, and in-store Amazon Pay. 1% on all other spends. Rewards as Amazon Pay balance.",
    cashbackStructure: "Rewards credited as Amazon Pay balance (usable on Amazon + offline stores accepting Amazon Pay). 5% Amazon / 2% Amazon Pay / 1% everywhere else.",
    loungeAccess: "None.",
    travelBenefits: "None. No travel insurance or airport benefits.",
    insuranceBenefits: "Zero lost card liability. Basic purchase protection. No medical or travel insurance.",
    fuelBenefits: "1% fuel surcharge waiver (max ₹100/month). ₹400-₹5,000 range.",
    diningBenefits: "1% back on dining (base rate). Amazon Pay offers at select restaurants occasionally.",
    movieBenefits: "1% back on BookMyShow. Amazon miniTV free with Prime.",
    golfBenefits: "None.",
    forexMarkup: "3.5% on foreign currency transactions.",
    milestoneRewards: "None. No milestone or spending-linked bonus rewards.",
    welcomeBenefits: "₹500 Amazon Pay cashback on first transaction. Free for life if spent ₹2L/year on some issuances.",
    currentOffers: "6% back during Amazon sale events (Prime members). Extra 1% on grocery category via Amazon Fresh. ICICI merchant offers: 10% off on Myntra, Ajio via Amazon Pay.",
    bestFor: "Amazon Prime members who shop heavily on Amazon. Zero joining fee makes it risk-free. Best for ₹1-3L annual Amazon spend.",
    worstFor: "Non-Amazon shoppers (1% is below average), anyone wanting real cashback (not Amazon Pay balance), travelers, premium seekers.",
    estimatedAnnualValue: 4500,
    bins: ["411262", "411263"],
  },
  {
    id: "card_idfc_wealth",
    name: "IDFC FIRST Wealth",
    bank: "IDFC FIRST Bank",
    network: "Visa",
    cardType: "credit",
    color: "#7B2D8E",
    annualFee: 999,
    joiningFee: 0,
    rewardStructure: "6 reward points per ₹100 on online. 3 reward points per ₹100 on offline. 10x on partner brands. 1 RP = ₹0.25. Effective 1.5% online / 0.75% offline.",
    cashbackStructure: "Points convertible to statement credit or vouchers. Not direct cashback. Redemption at 0.25-0.50 per point depending on option.",
    loungeAccess: "4 domestic + 2 international lounge visits per year. Via DreamFolks network.",
    travelBenefits: "Travel insurance ₹50 lakhs. Lost baggage ₹1 lakh. Trip delay cover. MakeMyTrip and EaseMyTrip offers.",
    insuranceBenefits: "Air accident cover ₹1 crore. Zero fraud liability. Purchase protection 120 days. Emergency medical abroad ₹10 lakhs.",
    fuelBenefits: "1% fuel surcharge waiver (max ₹200/month). Zero annual fee on maintaining ₹20K average monthly balance in IDFC savings account.",
    diningBenefits: "10x points on Swiggy, Zomato via IDFC rewards portal. EazyDiner partnerships.",
    movieBenefits: "Buy 1 Get 1 on BookMyShow (once per month, max ₹200).",
    golfBenefits: "None.",
    forexMarkup: "1.99% forex markup — one of the lowest in India. Excellent for international spending.",
    milestoneRewards: "Spend ₹3 lakhs/year: fee waiver + 3,000 bonus points. Spend ₹5 lakhs: additional 5,000 points. Never-expiring reward points.",
    welcomeBenefits: "Zero joining fee. 2,000 reward points on first spend. 500 points on setting up auto-pay.",
    currentOffers: "Flat 10% off on Amazon via IDFC portal (max ₹500). 20x points on international spends this quarter. BookMyShow BOGO every Friday.",
    bestFor: "International travelers (1.99% forex is killer). Budget-conscious users wanting decent benefits at ₹999. Those with IDFC FIRST savings account (zero fee).",
    worstFor: "Heavy domestic spenders (0.75% offline is low), lounge addicts (only 6 visits), miles accumulators.",
    estimatedAnnualValue: 10000,
    bins: ["422222", "422223"],
  },
  {
    id: "card_au_zenith_plus",
    name: "AU Zenith+",
    bank: "AU Small Finance Bank",
    network: "Mastercard",
    cardType: "credit",
    color: "#B5121B",
    annualFee: 9999,
    joiningFee: 9999,
    rewardStructure: "33 Vkaash reward points per ₹100 on weekends. 22 Vkaash per ₹100 on weekdays. 1 Vkaash = ₹0.10-0.15. Effective rate: 3.3-5% on weekends, 2.2-3.3% on weekdays.",
    cashbackStructure: "Vkaash points redeemable for flights, hotels, vouchers, statement credit. No direct cashback. Best value via travel redemptions on AU portal.",
    loungeAccess: "Unlimited domestic lounge access (cardholder + guest). 12 international lounge visits via Priority Pass. Among the highest lounge benefits in the segment.",
    travelBenefits: "Travel insurance ₹2 crores. Lost baggage ₹3 lakhs. Trip delay insurance. Complimentary airport meet & greet (2 per year).",
    insuranceBenefits: "Air accident cover ₹2 crores. Zero fraud liability. Purchase protection 90 days. Emergency medical ₹20 lakhs abroad.",
    fuelBenefits: "1% fuel surcharge waiver (max ₹500/month). Higher cap than most cards.",
    diningBenefits: "20% off at 5,000+ partner restaurants. Culinary experiences and chef's table events. EazyDiner Prime membership equivalent.",
    movieBenefits: "Buy 1 Get 1 on BookMyShow, PVR, INOX (4 times/month, max ₹350 per ticket). Best movie benefit in market.",
    golfBenefits: "8 complimentary rounds per year at 50+ courses. Guest green fee 50% off. Club hire included.",
    forexMarkup: "2% on foreign currency transactions. Competitive for premium segment.",
    milestoneRewards: "Spend ₹10 lakhs: annual fee reversal as Vkaash. Spend ₹20 lakhs: 50,000 bonus Vkaash + Marriott/Accor voucher. Weekend spend multiplier makes milestones easier.",
    welcomeBenefits: "50,000 Vkaash on completing ₹50,000 spend in first 60 days (worth ₹5,000-₹7,500). Complimentary Priority Pass.",
    currentOffers: "5x Vkaash on all international spends. AU LIT app: extra 10% on utility payments. Flipkart special: 10x Vkaash during Big Billion Days. Zero-cost EMI on all spends ₹10K+.",
    bestFor: "Weekend spenders (5% effective rate is market-leading), frequent diners, movie buffs (4x BOGO), and those wanting premium lounge access without Axis Magnus-level fees.",
    worstFor: "Purely weekday spenders (2.2% is average), those outside AU bank ecosystem, international-heavy spenders wanting sub-2% forex.",
    estimatedAnnualValue: 40000,
    bins: ["553737", "553738", "553739"],
  },
];

async function main() {
  await prisma.cardReport.deleteMany();
  await prisma.cardBIN.deleteMany();
  await prisma.cardProduct.deleteMany();

  for (const card of cards) {
    const { bins, ...cardData } = card;
    await prisma.cardProduct.create({ data: cardData });
    for (const bin of bins) {
      await prisma.cardBIN.create({
        data: {
          bin,
          bank: card.bank,
          network: card.network,
          type: card.cardType,
          tier: card.name.includes("Magnus") || card.name.includes("Zenith") ? "signature" : card.name.includes("Regalia") || card.name.includes("Atlas") ? "platinum" : "classic",
          country: "IN",
          cardProductId: card.id,
        },
      });
    }
  }

  const total = await prisma.cardProduct.count();
  const binCount = await prisma.cardBIN.count();
  console.log(`CardDNA seed complete: ${total} cards, ${binCount} BIN entries`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
